version: '3.9'

services:
  ellis-app:
    build: .
    container_name: ellis-container
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
